name = "nulldown"

compatibility_date = "2025-04-03"

# Tell Pages where your built static assets are
pages_build_output_dir = "dist"

# R2 binding - must match env.R2_BUCKET in functions code
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "nulldown"
preview_bucket_name = "nulldown-preview"

# 272f4fd9d668c5b64f0fe15702351709
