import React, { useCallback, useEffect, useRef, useState } from "react";
import useEditorStore, { type EditorState } from "../stores/editorStore";
import useStorageStore from "../stores/storageStore";
import { useDraftStorage } from "../hooks/useLocalStorage";
import EditorToolbar from "./editor/components/EditorToolbar";
import ErrorBanner from "./editor/components/ErrorBanner";
import EditorPane from "./editor/components/EditorPane";
import PreviewPane from "./editor/components/PreviewPane";
import HelpersDock from "./editor/components/HelpersDock";
import ShareSuccessView from "./editor/components/ShareSuccessView";
import SettingsModal from "./editor/components/SettingsModal";
import { useShareDrop } from "./editor/hooks/useShareDrop";
import { usePreviewToggle } from "./editor/hooks/usePreviewToggle";
import { useInsertText } from "./editor/hooks/useInsertText";

// const generateId = (title: string) => `${title !== undefined ? title.toLowerCase().replace(/ /g, '-').concat('-') : ""}${Math.random().toString(36).substring(2, 10)}`; // Not needed if ID is generated by backend

const EditorPage: React.FC = () => {
  const markdown = useEditorStore((state: EditorState) => state.textContent);

  const setTextContent = useEditorStore(
    (state: EditorState) => state.setTextContent,
  );

  const initializeStorage = useStorageStore((state) => state.initialize);

  const { clearDraft } = useDraftStorage(
    "nulldown_draft",
    markdown,
    setTextContent,
  );

  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    initializeStorage();
  }, [initializeStorage]);

  const insertText = useInsertText(textareaRef, markdown, setTextContent);

  const {
    editorHidden,
    isTransitioning,
    resetView,
    setEditMode,
    setPreviewMode,
    showPreview,
  } = usePreviewToggle();

  const { error, resetShare, setError, shareDrop, sharing, successUrl } =
    useShareDrop(markdown, clearDraft);

  const [settingsOpen, setSettingsOpen] = useState(false);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.preventDefault();
        setPreviewMode();
      }

      if (
        showPreview &&
        e.key.toLowerCase() === "i" &&
        !e.metaKey &&
        !e.ctrlKey &&
        !e.altKey
      ) {
        e.preventDefault();
        setEditMode();
      }

      if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
        e.preventDefault();
        if (markdown.trim() && !sharing) {
          shareDrop();
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [markdown, setEditMode, setPreviewMode, shareDrop, sharing, showPreview]);

  const newDrop = useCallback(() => {
    clearDraft();
    resetShare();
    resetView();

    setTimeout(() => {
      textareaRef.current?.focus();
    }, 0);
  }, [clearDraft, resetShare, resetView]);

  if (successUrl) {
    return (
      <ShareSuccessView
        successUrl={successUrl}
        onCopyError={setError}
        onNewDrop={newDrop}
      />
    );
  }

  return (
    <div className="fixed inset-0 flex flex-col">
      <EditorToolbar
        canShare={Boolean(markdown.trim())}
        isTransitioning={isTransitioning}
        sharing={sharing}
        onOpenSettings={() => setSettingsOpen(true)}
        onShare={shareDrop}
      />

      <SettingsModal
        open={settingsOpen}
        onClose={() => setSettingsOpen(false)}
      />

      <div
        className="flex-1 relative"
        style={{ height: "calc(100vh - 65px)" }}
        onClick={() => {
          if (showPreview) {
            setEditMode();
          }
        }}
      >
        {error && <ErrorBanner message={error} />}

        <EditorPane
          editorState={{ editorHidden }}
          markdown={markdown}
          showPreview={showPreview}
          textareaRef={textareaRef}
          onChange={setTextContent}
          onExitEdit={setPreviewMode}
        />

        <PreviewPane
          markdown={markdown}
          showPreview={showPreview}
        />
      </div>
    </div>
  );
};

export default EditorPage;
