import React, { useState, useEffect, useRef } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import useEditorStore, { type EditorState } from "../stores/editorStore"; // Import Zustand store and EditorState type

interface ShareApiResponse {
  id?: string;
  url?: string;
  error?: string; // If the API itself returns a structured error
  // Add any other fields the API might return on success/error
}

// const generateId = (title: string) => `${title !== undefined ? title.toLowerCase().replace(/ /g, '-').concat('-') : ""}${Math.random().toString(36).substring(2, 10)}`; // Not needed if ID is generated by backend

const EditorPage: React.FC = () => {
  // Use Zustand store for markdown content
  const markdown = useEditorStore((state: EditorState) => state.textContent);
  const setTextContent = useEditorStore((state: EditorState) => state.setTextContent);

  const [isClient, setIsClient] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successUrl, setSuccessUrl] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Effect 1: Set isClient to true once after initial mount
  useEffect(() => {
    setIsClient(true);
  }, []); // Empty dependency array ensures this runs only once

  // Effect 2: Load from localStorage on initial client-side readiness
  useEffect(() => {
    if (isClient) {
      const savedContent = localStorage.getItem('nulldown_draft');
      if (savedContent !== null) { // Check specifically for null, as "" is a valid state
        // This will set the store content from localStorage once when the client is ready.
        // If the store was already populated by other means, this might overwrite it.
        // For this app, it's likely the intended initial hydration.
        setTextContent(savedContent);
      }
    }
    // This effect runs when isClient becomes true, or if setTextContent were to change (it's stable).
    // Effectively, it runs once on the client-side after the initial setup.
  }, [isClient, setTextContent]);

  // Effect 3: Save to localStorage whenever markdown content changes, but only on client
  useEffect(() => {
    if (isClient) {
      localStorage.setItem('nulldown_draft', markdown);
    }
    // This effect runs when markdown (from the store) changes, or when isClient becomes true.
  }, [markdown, isClient]);

  const handleShare = async () => {
    if (!markdown.trim()) {
      setError("Cannot share empty content.");
      return;
    }
    setSharing(true);
    setError(null);
    setSuccessUrl(null);
    try {
      // Call the Cloudflare Function API endpoint
      const response = await fetch("/api/store", {
        method: "POST",
        headers: {
          "Content-Type": "text/plain", // Send as plain text as per functions/api/store.ts
        },
        body: markdown,
      });

      if (!response.ok) {
        const errorData = await response.text();
        throw new Error(errorData || `Failed to create drop: ${response.statusText}`);
      }

      const result: ShareApiResponse = await response.json();
      if (result.id && result.url) {
        setSuccessUrl(result.url);
        setTextContent(""); // Clear editor on success (via Zustand)
        localStorage.removeItem('nulldown_draft'); // Clear draft
      } else {
        setError(result.error || "Failed to create drop. Unknown error from API.");
      }
    } catch (err: any) {
      console.error("Share error:", err);
      setError(err.message || "An unexpected error occurred while sharing.");
    } finally {
      setSharing(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text).catch(err => {
      console.error('Failed to copy: ', err);
      setError("Failed to copy link.");
    });
  };

  const newDrop = () => {
    setTextContent(""); // Clear via Zustand
    setSuccessUrl(null);
    setError(null);
    setShowPreview(false);
    localStorage.removeItem('nulldown_draft');
    textareaRef.current?.focus();
  };

  if (successUrl) {
    return (
      <main className="flex-1 p-4 flex items-center justify-center">
        <div className="max-w-md w-full bg-card border border-border rounded-md p-6">
          <h2 className="text-xl mb-4 text-accent">Drop Created</h2>
          <p className="mb-4 text-sm">Your markdown has been dropped into the void.</p>
          <div className="flex mb-4">
            <input
              type="text"
              value={successUrl}
              readOnly
              className="flex-1 bg-background border border-border border-r-0 rounded-l-md p-2 text-sm text-foreground focus:outline-none"
            />
            <button 
              onClick={() => copyToClipboard(successUrl)}
              className="bg-accent text-black hover:bg-accent-hover rounded-r-md px-4 py-2 text-sm font-medium transition-colors"
            >
              Copy
            </button>
          </div>
          <div className="flex justify-between">
            <button 
              onClick={newDrop}
              className="border border-accent text-accent hover:bg-accent/10 rounded-md px-4 py-2 text-sm font-medium transition-colors"
            >
              New Drop
            </button>
            {/* For Vite, direct <a> tag or Link from react-router-dom */}
            <a 
              href={successUrl} 
              target="_blank" 
              rel="noopener noreferrer"
              className="bg-accent text-black hover:bg-accent-hover rounded-md px-4 py-2 text-sm font-medium transition-colors inline-block"
            >
              Visit Drop
            </a>
          </div>
        </div>
      </main>
    );
  }

  return (
    <div className="flex-1 p-4 flex flex-col overflow-y-auto overflow-x-hidden">
      <div className="relative flex flex-col md:flex-row gap-4 flex-1 min-h-0">
        <div className={`flex-1 flex flex-col ${showPreview ? 'hidden md:flex' : 'flex'} min-h-0`}>
          <textarea
            ref={textareaRef}
            id="markdown-input"
            value={markdown}
            onChange={(e) => setTextContent(e.target.value)}
            placeholder="Write your markdown here..."
            className="flex-1 w-full resize-none bg-card border border-border rounded-md p-4 text-foreground font-mono focus:border-accent focus:outline-none overflow-y-auto"
            autoFocus
          />
        </div>

        {showPreview && (
          <div 
            id="preview-container" 
            className="flex-1 flex flex-col bg-card border border-border rounded-md p-4 overflow-y-auto min-h-0"
          >
            <div id="preview-content" className="prose max-w-none">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {markdown || "*Preview will appear here*"}
              </ReactMarkdown>
            </div>
          </div>
        )}
      </div>

      {error && (
        <div id="error-message" className="bg-error/20 border border-error text-error-light p-3 rounded-md mt-4 text-sm flex-shrink-0">
          {error}
        </div>
      )}

      <div className="border-t border-border p-4 mt-4 flex-shrink-0">
        <div className="max-w-screen-xl mx-auto flex flex-wrap justify-between items-center gap-4">
          <div className="text-xs md:text-sm">NULLDOWN</div>
          <div className="flex gap-2">
            <button 
              id="toggle-preview-btn"
              onClick={() => setShowPreview(!showPreview)}
              className="border border-accent text-accent hover:bg-accent/10 rounded-md px-4 py-2 text-sm font-medium flex items-center transition-colors"
            >
              {showPreview ? "Hide Preview" : "Show Preview"}
            </button>
            <button 
              id="share-btn"
              onClick={handleShare}
              disabled={sharing || !markdown.trim()}
              className="bg-accent text-black hover:bg-accent-hover rounded-md px-4 py-2 text-sm font-medium flex items-center transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {sharing && <span className="inline-block w-4 h-4 border-2 border-black/30 border-t-black rounded-full animate-spin mr-2"></span>}
              {sharing ? "Sharing..." : "Share to the Void"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EditorPage; 